AllCops:
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - bin/**/*
  TargetRubyVersion: 2.7.1

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - config/routes.rb

Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 1500
